In [38]:
import pandas as pd

In [39]:
import numpy as np

In [40]:
from sklearn.cluster import KMeans

In [41]:
df = pd.read_csv('Weather Data in India from 1901 to 2017.csv')

In [42]:
df

Unnamed: 0  YEAR    JAN    FEB    MAR    APR    MAY    JUN    JUL    AUG  \
0             0  1901  17.99  19.43  23.49  26.41  28.28  28.60  27.49  26.98   
1             1  1902  19.00  20.39  24.10  26.54  28.68  28.44  27.29  27.05   
2             2  1903  18.32  19.79  22.46  26.03  27.93  28.41  28.04  26.63   
3             3  1904  17.77  19.39  22.95  26.73  27.83  27.85  26.84  26.73   
4             4  1905  17.40  17.79  21.78  24.84  28.32  28.69  27.67  27.47   
..          ...   ...    ...    ...    ...    ...    ...    ...    ...    ...   
112         112  2013  18.88  21.07  24.53  26.97  29.06  28.24  27.50  27.22   
113         113  2014  18.81  20.35  23.34  26.91  28.45  29.42  28.07  27.42   
114         114  2015  19.02  21.23  23.52  26.52  28.82  28.15  28.03  27.64   
115         115  2016  20.92  23.58  26.61  29.56  30.41  29.70  28.18  28.17   
116         116  2017  20.59  23.08  25.58  29.17  30.47  29.44  28.31  28.12   

       SEP    OCT    NOV    DEC  
0    26.26  25.08  21.73  18.95  
1    25.95  24.37  21.33  18.78  
2    26.34  24.57  20.96  18.29  
3    25.84  24.36  21.07  18.84  
4    26.29  26.16  22.07  18.71  
..     ...    ...    ...    ...  
112  26.87  25.63  22.18  19.69  
113  26.61  25.38  22.53  19.50  
114  27.04  25.82  22.95  20.21  
115  27.72  26.81  23.90  21.89  
116  28.11  27.24  23.92  21.47  

[117 rows x 14 columns]

In [43]:
cols = df.columns[1:]

In [44]:
cols

Index(['YEAR', 'JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP',
       'OCT', 'NOV', 'DEC'],
      dtype='object')

In [45]:
k=3

In [46]:
kmeans = KMeans(n_clusters = 3)

In [47]:
kmodel = kmeans.fit_predict(df[['YEAR', 'JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP',
       'OCT', 'NOV', 'DEC']])

In [48]:
kmodel

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2], dtype=int32)

In [49]:
df['cluster']=kmodel

In [50]:
df

Unnamed: 0  YEAR    JAN    FEB    MAR    APR    MAY    JUN    JUL    AUG  \
0             0  1901  17.99  19.43  23.49  26.41  28.28  28.60  27.49  26.98   
1             1  1902  19.00  20.39  24.10  26.54  28.68  28.44  27.29  27.05   
2             2  1903  18.32  19.79  22.46  26.03  27.93  28.41  28.04  26.63   
3             3  1904  17.77  19.39  22.95  26.73  27.83  27.85  26.84  26.73   
4             4  1905  17.40  17.79  21.78  24.84  28.32  28.69  27.67  27.47   
..          ...   ...    ...    ...    ...    ...    ...    ...    ...    ...   
112         112  2013  18.88  21.07  24.53  26.97  29.06  28.24  27.50  27.22   
113         113  2014  18.81  20.35  23.34  26.91  28.45  29.42  28.07  27.42   
114         114  2015  19.02  21.23  23.52  26.52  28.82  28.15  28.03  27.64   
115         115  2016  20.92  23.58  26.61  29.56  30.41  29.70  28.18  28.17   
116         116  2017  20.59  23.08  25.58  29.17  30.47  29.44  28.31  28.12   

       SEP    OCT    NOV    DEC  cluster  
0    26.26  25.08  21.73  18.95        0  
1    25.95  24.37  21.33  18.78        0  
2    26.34  24.57  20.96  18.29        0  
3    25.84  24.36  21.07  18.84        0  
4    26.29  26.16  22.07  18.71        0  
..     ...    ...    ...    ...      ...  
112  26.87  25.63  22.18  19.69        2  
113  26.61  25.38  22.53  19.50        2  
114  27.04  25.82  22.95  20.21        2  
115  27.72  26.81  23.90  21.89        2  
116  28.11  27.24  23.92  21.47        2  

[117 rows x 15 columns]

In [51]:
df[df.cluster==0].head()

Unnamed: 0  YEAR    JAN    FEB    MAR    APR    MAY    JUN    JUL    AUG  \
0           0  1901  17.99  19.43  23.49  26.41  28.28  28.60  27.49  26.98   
1           1  1902  19.00  20.39  24.10  26.54  28.68  28.44  27.29  27.05   
2           2  1903  18.32  19.79  22.46  26.03  27.93  28.41  28.04  26.63   
3           3  1904  17.77  19.39  22.95  26.73  27.83  27.85  26.84  26.73   
4           4  1905  17.40  17.79  21.78  24.84  28.32  28.69  27.67  27.47   

     SEP    OCT    NOV    DEC  cluster  
0  26.26  25.08  21.73  18.95        0  
1  25.95  24.37  21.33  18.78        0  
2  26.34  24.57  20.96  18.29        0  
3  25.84  24.36  21.07  18.84        0  
4  26.29  26.16  22.07  18.71        0

In [52]:
df[df.cluster==1].head()


Unnamed: 0  YEAR    JAN    FEB    MAR    APR    MAY    JUN    JUL    AUG  \
40          40  1941  18.33  20.28  24.24  27.49  28.89  28.52  27.54  27.43   
41          41  1942  18.07  20.06  23.87  26.79  28.82  28.81  27.28  26.62   
42          42  1943  18.32  19.47  23.31  25.56  27.82  27.80  27.16  26.66   
43          43  1944  18.00  19.07  22.54  25.63  28.93  28.39  27.42  27.11   
44          44  1945  17.33  19.37  23.28  25.52  28.31  28.81  27.39  26.98   

      SEP    OCT    NOV    DEC  cluster  
40  26.29  25.47  21.76  19.67        1  
41  26.03  24.56  21.85  18.75        1  
42  26.26  24.20  21.81  19.02        1  
43  26.08  24.49  21.51  19.32        1  
44  26.51  24.36  21.15  17.98        1

In [53]:
df[df.cluster==2].head()

Unnamed: 0  YEAR    JAN    FEB    MAR    APR    MAY    JUN    JUL    AUG  \
79          79  1980  18.81  20.47  23.24  27.55  28.94  28.25  27.33  26.93   
80          80  1981  18.40  20.44  23.26  26.65  28.51  28.40  27.28  26.85   
81          81  1982  18.76  19.52  22.37  26.15  27.72  28.20  27.68  26.98   
82          82  1983  18.38  19.81  22.68  25.67  28.02  28.60  27.51  27.14   
83          83  1984  18.28  19.42  23.98  26.66  28.88  28.43  26.94  27.17   

      SEP    OCT    NOV    DEC  cluster  
79  26.55  25.12  22.15  19.23        2  
80  26.36  24.74  21.43  18.87        2  
81  26.40  24.89  21.84  19.33        2  
82  26.48  24.56  21.50  19.08        2  
83  25.83  24.65  21.47  19.34        2

In [55]:
df

Unnamed: 0  YEAR    JAN    FEB    MAR    APR    MAY    JUN    JUL    AUG  \
0             0  1901  17.99  19.43  23.49  26.41  28.28  28.60  27.49  26.98   
1             1  1902  19.00  20.39  24.10  26.54  28.68  28.44  27.29  27.05   
2             2  1903  18.32  19.79  22.46  26.03  27.93  28.41  28.04  26.63   
3             3  1904  17.77  19.39  22.95  26.73  27.83  27.85  26.84  26.73   
4             4  1905  17.40  17.79  21.78  24.84  28.32  28.69  27.67  27.47   
..          ...   ...    ...    ...    ...    ...    ...    ...    ...    ...   
112         112  2013  18.88  21.07  24.53  26.97  29.06  28.24  27.50  27.22   
113         113  2014  18.81  20.35  23.34  26.91  28.45  29.42  28.07  27.42   
114         114  2015  19.02  21.23  23.52  26.52  28.82  28.15  28.03  27.64   
115         115  2016  20.92  23.58  26.61  29.56  30.41  29.70  28.18  28.17   
116         116  2017  20.59  23.08  25.58  29.17  30.47  29.44  28.31  28.12   

       SEP    OCT    NOV    DEC  cluster  
0    26.26  25.08  21.73  18.95        0  
1    25.95  24.37  21.33  18.78        0  
2    26.34  24.57  20.96  18.29        0  
3    25.84  24.36  21.07  18.84        0  
4    26.29  26.16  22.07  18.71        0  
..     ...    ...    ...    ...      ...  
112  26.87  25.63  22.18  19.69        2  
113  26.61  25.38  22.53  19.50        2  
114  27.04  25.82  22.95  20.21        2  
115  27.72  26.81  23.90  21.89        2  
116  28.11  27.24  23.92  21.47        2  

[117 rows x 15 columns]

In [57]:
df['JAN']

0      17.99
1      19.00
2      18.32
3      17.77
4      17.40
       ...  
112    18.88
113    18.81
114    19.02
115    20.92
116    20.59
Name: JAN, Length: 117, dtype: float64

In [58]:
x = df['JAN'].values.reshape(-1,1)

In [59]:
x

array([[17.99],
       [19.  ],
       [18.32],
       [17.77],
       [17.4 ],
       [17.5 ],
       [19.27],
       [18.35],
       [17.79],
       [18.14],
       [18.52],
       [18.6 ],
       [18.2 ],
       [18.96],
       [17.93],
       [18.52],
       [18.16],
       [17.25],
       [18.78],
       [18.27],
       [18.61],
       [18.3 ],
       [18.23],
       [18.06],
       [17.53],
       [18.65],
       [18.15],
       [18.66],
       [18.25],
       [17.75],
       [19.34],
       [18.72],
       [17.84],
       [17.8 ],
       [17.54],
       [18.06],
       [18.02],
       [18.15],
       [18.4 ],
       [18.1 ],
       [18.33],
       [18.07],
       [18.32],
       [18.  ],
       [17.33],
       [18.31],
       [17.72],
       [18.25],
       [19.01],
       [18.36],
       [19.09],
       [18.67],
       [18.11],
       [17.77],
       [18.42],
       [18.01],
       [18.2 ],
       [19.5 ],
       [18.39],
       [18.31],
       [18.89],
       [17.54],
       [

In [60]:
y = df['cluster'].values.reshape(-1,1)

In [61]:
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
    

In [62]:
x = x.astype('int')

In [63]:
x

array([[17],
       [19],
       [18],
       [17],
       [17],
       [17],
       [19],
       [18],
       [17],
       [18],
       [18],
       [18],
       [18],
       [18],
       [17],
       [18],
       [18],
       [17],
       [18],
       [18],
       [18],
       [18],
       [18],
       [18],
       [17],
       [18],
       [18],
       [18],
       [18],
       [17],
       [19],
       [18],
       [17],
       [17],
       [17],
       [18],
       [18],
       [18],
       [18],
       [18],
       [18],
       [18],
       [18],
       [18],
       [17],
       [18],
       [17],
       [18],
       [19],
       [18],
       [19],
       [18],
       [18],
       [17],
       [18],
       [18],
       [18],
       [19],
       [18],
       [18],
       [18],
       [17],
       [17],
       [17],
       [18],
       [18],
       [18],
       [17],
       [18],
       [18],
       [18],
       [18],
       [18],
       [17],
       [17],
       [18],
       [18],

In [65]:
import seaborn as sns

In [67]:
import matplotlib.pyplot as plt

In [70]:
cols

Index(['YEAR', 'JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP',
       'OCT', 'NOV', 'DEC'],
      dtype='object')

In [72]:
df[cols]

YEAR    JAN    FEB    MAR    APR    MAY    JUN    JUL    AUG    SEP  \
0    1901  17.99  19.43  23.49  26.41  28.28  28.60  27.49  26.98  26.26   
1    1902  19.00  20.39  24.10  26.54  28.68  28.44  27.29  27.05  25.95   
2    1903  18.32  19.79  22.46  26.03  27.93  28.41  28.04  26.63  26.34   
3    1904  17.77  19.39  22.95  26.73  27.83  27.85  26.84  26.73  25.84   
4    1905  17.40  17.79  21.78  24.84  28.32  28.69  27.67  27.47  26.29   
..    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
112  2013  18.88  21.07  24.53  26.97  29.06  28.24  27.50  27.22  26.87   
113  2014  18.81  20.35  23.34  26.91  28.45  29.42  28.07  27.42  26.61   
114  2015  19.02  21.23  23.52  26.52  28.82  28.15  28.03  27.64  27.04   
115  2016  20.92  23.58  26.61  29.56  30.41  29.70  28.18  28.17  27.72   
116  2017  20.59  23.08  25.58  29.17  30.47  29.44  28.31  28.12  28.11   

       OCT    NOV    DEC  
0    25.08  21.73  18.95  
1    24.37  21.33  18.78  
2    24.57  20.96  18.29  
3    24.36  21.07  18.84  
4    26.16  22.07  18.71  
..     ...    ...    ...  
112  25.63  22.18  19.69  
113  25.38  22.53  19.50  
114  25.82  22.95  20.21  
115  26.81  23.90  21.89  
116  27.24  23.92  21.47  

[117 rows x 13 columns]

In [73]:
kmeans = KMeans(n_clusters=3)

In [76]:
kmodel= kmeans.fit_predict(df[cols])

In [ ]:
kmodel